# Microsoft Translator API
translator.api.key=
translator.api.region=westeurope
translator.api.endpoint=https://api.cognitive.microsofttranslator.com/translate?api-version=3.0

# Groq API
groq.api.token=
groq.api.model=llama-3.3-70b-versatile
groq.api.max.tokens=1024
groq.api.temperature=0.7

# Stripe API (mode test)
stripe.api.key.pk=
stripe.api.key.sk=
stripe.currency=eur

