# Microsoft Translator API
translator.api.key=3fJD03acxkEaUP2S1bWVpJKcWn6aZPttzSgJnaSdO5FRoHPaZ0t5JQQJ99CBAC5RqLJXJ3w3AAAbACOGjpg4
translator.api.region=westeurope
translator.api.endpoint=https://api.cognitive.microsofttranslator.com/translate?api-version=3.0

# Groq API
groq.api.token=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
groq.api.model=llama-3.3-70b-versatile
groq.api.max.tokens=1024
groq.api.temperature=0.7

# Stripe API (mode test)
stripe.api.key.pk=pk_test_51T407NE0yXSFcl6GqdP9MRRWGsx65ITRQ0ixyPNeyT9Mi6J1iE6iqmaxRhznUlnf3sok1fcElCZLonZiGnX9N2qZ00LcwWbM6T
stripe.api.key.sk=sk_test_51T407NE0yXSFcl6GktlSiiZ49GUJlnKqTmQPLHEmQNnXSbXhw13XdWPOH5i9CSTPUvWSqGPC4AFsxC6yl5SMKZmA00EeMPVeFM
stripe.currency=eur

